<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN2WMgAx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN2WMgAx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN2WMgAx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN2WMgAx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN2WMgAx\App_KernelDevDebugContainer([
    'container.build_hash' => 'N2WMgAx',
    'container.build_id' => '893420a5',
    'container.build_time' => 1584499522,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN2WMgAx');
