<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQLt0pTB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQLt0pTB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQLt0pTB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQLt0pTB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQLt0pTB\App_KernelDevDebugContainer([
    'container.build_hash' => 'QLt0pTB',
    'container.build_id' => '7a23875c',
    'container.build_time' => 1584830258,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQLt0pTB');
