<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAiuxXgf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAiuxXgf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAiuxXgf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAiuxXgf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAiuxXgf\App_KernelDevDebugContainer([
    'container.build_hash' => 'AiuxXgf',
    'container.build_id' => 'd4413ce3',
    'container.build_time' => 1584501862,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAiuxXgf');
